-- Generated by Mocodo 4.2.1

CREATE TABLE ALBUMS (
  PRIMARY KEY (id_album),
  id_album     INTEGER NOT NULL,
  title        VARCHAR(42),
  release_date DATE,
  img          VARCHAR(42),
  id_art       INTEGER NOT NULL
);

CREATE TABLE ARTISTES (
  PRIMARY KEY (id_art),
  id_art       INTEGER NOT NULL,
  nom_de_scene VARCHAR(42),
  nom          VARCHAR(42),
  prenom       VARCHAR(42)
);

CREATE TABLE A_GENRE (
  PRIMARY KEY (id_album, libelle_genre),
  id_album      INTEGER NOT NULL,
  libelle_genre VARCHAR(42) NOT NULL
);

CREATE TABLE EST_DANS (
  PRIMARY KEY (id_playlist, id_album),
  id_playlist INTEGER NOT NULL,
  id_album    INTEGER NOT NULL
);

CREATE TABLE PLAYLIST (
  PRIMARY KEY (id_playlist),
  id_playlist INTEGER NOT NULL,
  nom         VARCHAR(42),
  email       VARCHAR(42) NOT NULL
);

CREATE TABLE SUIT (
  PRIMARY KEY (id_art, email),
  id_art INTEGER NOT NULL,
  email  VARCHAR(42) NOT NULL
);

CREATE TABLE UTILISATEURS (
  PRIMARY KEY (email),
  email          VARCHAR(42) NOT NULL,
  nom            VARCHAR(42),
  prenom         VARCHAR(42),
  date_naissance VARCHAR(42),
  mdp            VARCHAR(42)
);

ALTER TABLE ALBUMS ADD FOREIGN KEY (id_art) REFERENCES ARTISTES (id_art);

ALTER TABLE A_GENRE ADD FOREIGN KEY (id_album) REFERENCES ALBUMS (id_album);

ALTER TABLE EST_DANS ADD FOREIGN KEY (id_album) REFERENCES ALBUMS (id_album);
ALTER TABLE EST_DANS ADD FOREIGN KEY (id_playlist) REFERENCES PLAYLIST (id_playlist);

ALTER TABLE PLAYLIST ADD FOREIGN KEY (email) REFERENCES UTILISATEURS (email);

ALTER TABLE SUIT ADD FOREIGN KEY (email) REFERENCES UTILISATEURS (email);
ALTER TABLE SUIT ADD FOREIGN KEY (id_art) REFERENCES ARTISTES (id_art);
