-- Generated by Mocodo 4.2.1

CREATE TABLE ALBUMS (
  PRIMARY KEY (id_album),
  id_album     NUMBER NOT NULL,
  title        VARCHAR(42),
  release_date DATE,
  img          BLOB,
  id_art       VARCHAR(42) NOT NULL
);

CREATE TABLE ARTISTES (
  PRIMARY KEY (id_art),
  id_art       VARCHAR(42) NOT NULL,
  nom_de_scene VARCHAR(42),
  nom          VARCHAR(42),
  prenom       VARCHAR(42)
);

CREATE TABLE A_GENRE (
  PRIMARY KEY (id_album, id_genre),
  id_album NUMBER NOT NULL,
  id_genre VARCHAR(42) NOT NULL
);

CREATE TABLE GENRE (
  PRIMARY KEY (id_genre),
  id_genre VARCHAR(42) NOT NULL,
  libelle  VARCHAR(42)
);

CREATE TABLE PLAYLIST (
  PRIMARY KEY (id_user, id_album),
  id_user  VARCHAR(42) NOT NULL,
  id_album NUMBER NOT NULL
);

CREATE TABLE SUIT (
  PRIMARY KEY (id_art, id_user),
  id_art  VARCHAR(42) NOT NULL,
  id_user VARCHAR(42) NOT NULL
);

CREATE TABLE UTILISATEURS (
  PRIMARY KEY (id_user),
  id_user        VARCHAR(42) NOT NULL,
  nom            VARCHAR(42),
  prenom         VARCHAR(42),
  date_naissance VARCHAR(42),
  mdp            VARCHAR(42)
);

ALTER TABLE ALBUMS ADD FOREIGN KEY (id_art) REFERENCES ARTISTES (id_art);

ALTER TABLE A_GENRE ADD FOREIGN KEY (id_genre) REFERENCES GENRE (id_genre);
ALTER TABLE A_GENRE ADD FOREIGN KEY (id_album) REFERENCES ALBUMS (id_album);

ALTER TABLE PLAYLIST ADD FOREIGN KEY (id_album) REFERENCES ALBUMS (id_album);
ALTER TABLE PLAYLIST ADD FOREIGN KEY (id_user) REFERENCES UTILISATEURS (id_user);

ALTER TABLE SUIT ADD FOREIGN KEY (id_user) REFERENCES UTILISATEURS (id_user);
ALTER TABLE SUIT ADD FOREIGN KEY (id_art) REFERENCES ARTISTES (id_art);
